[package]
name = "serendip"
description = "Read Fluke is2 thermal imagery. Extract the thermal data and convert to kelvin."
version = "0.3.0"
authors = ["Arthur Nieuwland <anieuwland@nimmerfort.eu>"]
edition = "2024"
license = "EUPL-1.2"
repository = "https://github.com/anieuwland/serendip/"
exclude = ["thermograms/"]

[lib]
name = "serendip"
path = "src/serendip.rs"

[[bin]]
name = "serendip"
path = "src/main.rs"

[dependencies]
env_logger = "0.11"
log = "0.4"
prost = "0.13"
zerocopy = "0.8"
zip = "2"
